services:
  auth-svc:
    build: .
    container_name: auth-svc
    environment:
      - KV_VIPER_FILE=./config_docker.yaml
    ports:
      - "8001:8000"
    networks:
      - chains-net

  auth-svc-postgres:
    image: postgres:15
    container_name: auth-svc-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "7001:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - chains-net

  auth-svc-swagger:
    image: swaggerapi/swagger-ui
    container_name: auth-svc-swagger
    environment:
      - SWAGGER_JSON=/docs/api-bundled.yaml
    volumes:
      - ./docs:/docs:ro
    ports:
      - "5001:8080"
    networks:
      - chains-net

volumes:
  pgdata:

networks:
  chains-net:
    external: true
